### PR TITLE
travis: add PHP 7.1

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by gherkins** [comment]
hm, the php-coveralls seems not to cover php 5.3 & 5.4 in the current version...

**Comment by TomasVotruba** [comment]
:+1:

**Comment by TomasVotruba** [comment]
Coverage should be run only against one PHP version. I use PHP 7.0.
It's duplicated knowledge and it slows down test process with Xdebug a lot.

**Comment by gherkins** [comment]
Good point. Didn't really think about that.
But makes perfect sense, i created an issue for that https://github.com/gherkins/regexpbuilderphp/issues/23

**Pull request merged**
